M48
; DRILL file {KiCad 7.0.11} date Monday, January 20, 2025 at 01:35:28 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-20T01:35:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X148.1Y-81.93
X148.11Y-112.3
X182.1Y-81.94
X182.1Y-112.3
M30
