M48
; DRILL file {KiCad 7.0.11} date Monday, January 20, 2025 at 01:41:05 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-20T01:41:05+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X135.35Y-68.57
X135.35Y-98.95
X169.35Y-68.58
X169.36Y-98.95
M30
